// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: users.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const findUserByDiscordID = `-- name: FindUserByDiscordID :one
SELECT id, discord_id, pseudo, tag FROM "users"
WHERE discord_id = $1 LIMIT 1
`

func (q *Queries) FindUserByDiscordID(ctx context.Context, discordID string) (User, error) {
	row := q.db.QueryRow(ctx, findUserByDiscordID, discordID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.DiscordID,
		&i.Pseudo,
		&i.Tag,
	)
	return i, err
}

const persistUser = `-- name: PersistUser :exec
INSERT INTO "users" (
    id, discord_id, pseudo, tag
) VALUES (
    $1, $2, $3, $4
)
ON CONFLICT (discord_id)
DO UPDATE SET
    pseudo = EXCLUDED.pseudo,
    tag = EXCLUDED.tag
`

type PersistUserParams struct {
	ID        pgtype.UUID
	DiscordID string
	Pseudo    string
	Tag       string
}

func (q *Queries) PersistUser(ctx context.Context, arg PersistUserParams) error {
	_, err := q.db.Exec(ctx, persistUser,
		arg.ID,
		arg.DiscordID,
		arg.Pseudo,
		arg.Tag,
	)
	return err
}
